//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_contacts
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public string contactname { get; set; }
        public string sex { get; set; }
        public string position { get; set; }
        public string cellphone { get; set; }
        public string telphone { get; set; }
        public string email { get; set; }
        public string qq { get; set; }
        public string fax { get; set; }
        public string remarks { get; set; }
        public Nullable<int> createuid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
