//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Customer_address
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public string addressname { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public Nullable<int> createuid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
