//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Product
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public string procode { get; set; }
        public string proname { get; set; }
        public string drawingno { get; set; }
        public string prounit { get; set; }
        public string prospecification { get; set; }
        public Nullable<double> pronetweight { get; set; }
        public Nullable<double> progrossweight { get; set; }
        public Nullable<int> protype { get; set; }
        public Nullable<int> filepath { get; set; }
    }
}
