//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductDraw
    {
        public int id { get; set; }
        public int pid { get; set; }
        public string drawingno { get; set; }
        public string remark { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public string filepath { get; set; }
    }
}
