//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductbasicPrice
    {
        public int id { get; set; }
        public Nullable<int> productid { get; set; }
        public string version { get; set; }
        public Nullable<decimal> returnmatprice { get; set; }
        public Nullable<decimal> materialprice { get; set; }
        public Nullable<decimal> machineprice { get; set; }
        public Nullable<decimal> manageprice { get; set; }
        public Nullable<decimal> otherprice { get; set; }
        public Nullable<decimal> totalprice { get; set; }
        public string pricebasicremark { get; set; }
    }
}
