//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMSservice.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Suppliers
    {
        public int id { get; set; }
        public string supplierno { get; set; }
        public string suppliername { get; set; }
        public string suppliertype { get; set; }
        public string telphone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string bank { get; set; }
        public string accountname { get; set; }
        public string accountno { get; set; }
        public string taxcode { get; set; }
        public string legalperson { get; set; }
        public string businessscope { get; set; }
        public string remarks { get; set; }
        public Nullable<int> createuid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string simplename { get; set; }
    }
}
