//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMS.Client.MRP.Entities
{
    using System;
    using System.Collections.Generic;

    public partial class T_ApplyUseOrder
    {
        /// <summary>
        /// 申领单号
        /// </summary>
        public string ApplyUseNo { get; set; }
        /// <summary>
        /// 申领部门
        /// </summary>
        public string Dept { get; set; }
        /// <summary>
        /// 申领部门编码
        /// </summary>
        public string DeptDesc { get; set; }
        /// <summary>
        /// 申领日期
        /// </summary>
        public string ApplyUseDate { get; set; }
        /// <summary>
        /// 用途类型
        /// </summary>
        public short ApplyUseType { get; set; }
        /// <summary>
        /// 领用人
        /// </summary>
        public string User { get; set; }
        /// <summary>
        /// 领用人描述
        /// </summary>
        public string Userdesc { get; set; }
        /// <summary>
        /// 销售订单号
        /// </summary>
        public string SaleNo { get; set; }
        /// <summary>
        /// 生产指令单号
        /// </summary>
        public string ProductOrderNo { get; set; }
        /// <summary>
        /// 申请人
        /// </summary>
        public string Applicant { get; set; }
        /// <summary>
        /// 申请人描述
        /// </summary>
        public string ApplicantDesc { get; set; }
        public string Register { get; set; }
        public string RegisterDesc { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
    }
}
