//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMS.Client.MRP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Invoice
    {
        public string id { get; set; }
        public string invoiceno { get; set; }
        public string pono { get; set; }
        public decimal amount { get; set; }
        public DateTime paydate { get; set; }
        public string oper { get; set; }
        public string operdesc { get; set; }
        public string attachment { get; set; }
        public string remark { get; set; }
        public string register { get; set; }
        public string registerdesc { get; set; }
        public Nullable<System.DateTime> registdate { get; set; }
    }
}
