//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMS.Client.MRP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PurchaseOrder
    {
        public string pono { get; set; }
        public string applydate { get; set; }
        public short potype { get; set; }
        public decimal amount { get; set; }
        public short arrivalstatus { get; set; }
        public string buyer { get; set; }
        public string buyerdesc { get; set; }
        public string saleno { get; set; }
        public string demandarrivaldate { get; set; }
        public string actualarrivaldate { get; set; }
        public string arrivalremark { get; set; }
        public short postatus { get; set; }
        public string applydept { get; set; }
        public string applydeptdesc { get; set; }
        public string applicant { get; set; }
        public string applicantdesc { get; set; }
        public string register { get; set; }
        public string registerdesc { get; set; }
        public Nullable<System.DateTime> registdate { get; set; }
        public short paymentstatus { get; set; }
        public string approvaldate { get; set; }
        public string approval { get; set; }
        public string approvaldesc { get; set; }
        public string sendapprovaldate { get; set; }
        public string approvalremark { get; set; }
    }
}
