//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEMS.Client.MRP.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_StandardMaterial
    {
        /// <summary>
        /// 物资编码
        /// </summary>
        public string MatCode { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public string Desc { get; set; }
        /// <summary>
        /// 物资类型
        /// </summary>
        public string MatTypeCode { get; set; }
        //public decimal Price { get; set; }
        /// <summary>
        /// 物资型号
        /// </summary>
        public string MatModeCode { get; set; }
    }
}
